#!/usr/bin/env bash
# This script displays information about subdomains

get_record_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
        destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_record_info "$1" "$2"
