#!/bin/bash

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Configure redirection
new_lines="return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;"

sed -i "s@^\s*location \/redirect_me {\$@$new_lines\n}@" /etc/nginx/sites-available/default

# Restart Nginx
systemctl restart nginx
