#!/bin/bash

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sed -i '/^\s*error_page 404/c\        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
systemctl restart nginx
