#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80

# Install Nginx
apt-get update
apt-get install nginx -y

# Configure Nginx to listen on port 80
echo "server {
    listen 80;
    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
