#!/usr/bin/env bash
# This script displays a list of currently running processes, including all processes
# for all users, even those that don't have a TTY, and displays them in a
# user-oriented format, showing process hierarchy.
# Use the ps command with options to display all processes in a tree-like format

ps axjf
