#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59 using while loop (for and until are forbidden)

hours=0

while [ $hours -le 12 ]
do
	minutes=1
	while [ $minutes -le 59 ]
	do
		printf "%02d:%02d\n" $hours $minutes
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
done
