#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes: display hours from 0 to 12, display minutes from 1 to 59 using while loop (for and until are forbidden)

hours=0

while [ $hours -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( munite++ ))
	done
	(( hour++ ))
done
