#!/usr/bin/env bash
# This script takes two arguments: the new IP address for the
# localhost hostname and the new IP address for the facebook.com hostname
# It then creates a new /etc/hosts file with these IP addresses and sets 
# it as the new hosts file, while also backing up the old hosts file.
# Finally, it restarts the networking service to apply the changes.

if [ $# -ne 2 ]; then
	echo "Usage: 0-change_your_home_IP {LOCAL_IP_ADDRESS} {REMOTE_IP_ADDRESS}"
	exit 1
fi

# Set up the new /etc/hosts file
echo "$2 facebook.com" > /tmp/hosts
echo "$1 localhost" >> /tmp/hosts
echo "127.0.0.1 localhost" >> /tmp/hosts
echo "::1 localhost" >> /tmp/hosts

# Backup the old /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Replace the old /etc/hosts file with the new one
sudo mv /tmp/hosts /etc/hosts

# Restart the networking service to apply changes
sudo service networking restart
