#!/usr/bin/env bash
# This script changes nginx configuration to run as nginx user and listen to port 8080

# Replace the user in nginx.conf
sed -i 's/user root;/user nginx;/g' /etc/nginx/nginx.conf

# Replace the listen directive in the default server block to port 8080
sed -i 's*listen       80 default_server;*listen       8080 default_server;*g' /etc/nginx/conf.d/default.conf

# Test configuration and restart nginx
nginx -t && service nginx restart

# Verifies if nginx runs as user nginx and listens on port 8080
if [ "$(ps auxff | grep ngin[x] | awk '{print $1}')" == "nginx" ] 
then
    echo "nginx is running as the user nginx."
fi

if nc -z 127.0.0.1 8080; then
    echo "nginx listens to port 8080."
fi
